@startuml

node "Subscription Service" {
    component "subscription-service" <<Spring Boot 2.1.2>> as subscriptionService #Yellow
    database "Subscriptions DB" <<MySQL>> as database #Yellow
}


node "Events Service" {
    component "events-service" <<Any>> as eventsService #Yellow
}

node "Email Service" {
    component "email-service" <<Any>> as emailService #Yellow
}

subscriptionService --> database
subscriptionService -up-> eventsService
subscriptionService -up-> emailService

@enduml
