spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:mysql://subscription-mysql/subscription?useSSL=false&allowPublicKeyRetrieval=true
    username: subscription
    password: subscription
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

jwtAuthToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE1NDg1MzQ2MjMsImV4cCI6MTU4MDA3MDYyMywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.BBOKMny51X3oP8SZqTfhHgcvORHgo93AYBUcBLNNAE9eWczYzfaiF4lPpjY1vpfzJmBNaA7T6HtXU1xWpbJqNw